version: '3.8'

services:
  systemplus-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: systemplus-assistant
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - systemplus-network

networks:
  systemplus-network:
    driver: bridge
